/** A single trip record as stored in localStorage. */
export interface Trip {
  id: string;
  countryCode: string; // ISO 3166-1 alpha-2
  countryName: string;
  cities: string[];
  visitDate: string; // "YYYY-MM" or "YYYY-MM-DD"
  note: string; // "" when absent
  createdAt: string; // ISO 8601
  updatedAt: string; // ISO 8601
}

/** Form input — no id or timestamps (generated by the service). */
export interface TripInput {
  countryCode: string;
  countryName: string;
  cities: string[];
  visitDate: string;
  note: string;
}

/**
 * Client-side derived grouping — not persisted.
 * Computed from the trips array on every render.
 */
export interface CountrySummary {
  countryCode: string;
  countryName: string;
  cityCount: number;
  tripCount: number;
  mostRecentVisit: string;
}

/** Static entry from src/data/countries.ts (ISO 3166-1 list). */
export interface CountryOption {
  code: string;
  name: string;
}
